Add async logout(options) method
rkusa/koa-passport pull request #188
Opened 2022-12-05 16:18 UTC by lehni

Passport v0.6.0 added new `options` and `callback` arguments to `req.logout(options, callback)`.  
`ctx.logout()` should thus become `async` and use this callback.

2022-12-05 16:35 UTC, lehni commented
I should add that when no callback is provided, which is currently the case in koa-passport, and a session manager is in use, then this error is thrown:

> `req#logout requires a callback function`

The reason is here:

https://github.com/jaredhanson/passport/blob/42630cbd1ffd44d146ff96f0a4be6f3c12f81d75/lib/http/request.js#L65

More details:

https://github.com/jaredhanson/passport/issues/902

2023-01-11 12:50 UTC, rkusa requested changes
Thanks for the PR! I have two things in the inline comments.

Mostly a note to myself: I think I have to consider this a breaking API change and bump the major version of `koa-passport` for this.

2023-01-11 12:50 UTC, rkusa commented on lib/framework/koa.js
> -    const login  = req.login
I think I'd prefer to keep this line around. IIRC, the reason for it was that if anyone messes with the request object after `koa-passport` got mounted, it does not affect the login/logout logic here.

2023-01-11 12:50 UTC, rkusa commented on lib/framework/koa.js
> -    // add aliases for passport's request extensions to Koa's context
Nit: I don't see a reason to remove the comment

2023-02-04 11:02 UTC, lehni commented on lib/framework/koa.js
> -    const login  = req.login
Good point. I've just addressed this! Thank you for the review, and apologies for taking so long.

2023-02-04 11:03 UTC, lehni commented on lib/framework/koa.js
> -    // add aliases for passport's request extensions to Koa's context
You're right! That was an unintentional change.

2023-02-06 14:03 UTC, merged

2023-02-06 14:03 UTC, rkusa commented
Thanks for the changes and again for the PR! 👍
I'll create a new release later today.

2023-02-07 12:20 UTC, lehni commented
Thank you @rkusa !